inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: either
