inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
